export const pets = [{
    id:'9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
    type: 'dog',
    name: 'porky',
    isAdopted: false,
    image: 'https://static.dw.com/image/47715732_101.jpg',
    height: 0.50,
    weight: 20,
    color: '#fff',
    bio: 'very cute, very fat',
    hypoallergenic: false,
    dietRestrictions: 'none',
    breed: 'pug',
    featured: true
},{
    id:'1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed',
    type: 'dog',
    name: 'flash',
    isAdopted: false,
    image: 'https://parade.com/wp-content/uploads/2020/10/fastest-dog-breeds.jpg',
    height: 0.50,
    weight: 20,
    color: null,
    bio: 'very cute, very fat',
    hypoallergenic: false,
    dietRestrictions: 'none',
    breed: 'pug',
    featured: true
},{
    id:'9b1deb4d-3ddd-4bad-9bdd-ghed7b3dcb6d',
    type: 'dog',
    name: 'cookie',
    isAdopted: false,
    image: 'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12164822/Cairn-Terrier-sitting-in-the-grass.jpg',
    height: 0.50,
    weight: 20,
    color: null,
    bio: 'very cute, very fat',
    hypoallergenic: false,
    dietRestrictions: 'none',
    breed: 'pug',
    featured: true
},{
    id:'1b9d6bcd-bfgd-4b2d-9uid-ab8dfbbd4bed',
    type: 'cat',
    name: 'billy',
    isAdopted: false,
    image: 'https://kerenagam.co.il/wp-content/uploads/2021/06/Thinking-of-getting-a-cat.png',
    height: 0.50,
    weight: 20,
    color: null,
    bio: 'very cute, very fat',
    hypoallergenic: false,
    dietRestrictions: 'none',
    breed: 'pug',
    featured: false
},{
    id:'710b962e-041c-11e1-9234-0123456789ab',
    type: 'dog',
    name: 'zamir',
    isAdopted: false,
    image: 'https://images.ctfassets.net/440y9b545yd9/1MZTD1yQiSBtdlPguEbRr9/fb88d756610b9d077c098061c50ea288/Cool-summer-gadgets-pets-hero850.jpg',
    height: 0.50,
    weight: 20,
    color: null,
    bio: 'very cute, very fat',
    hypoallergenic: false,
    dietRestrictions: 'none',
    breed: 'pug',
    featured: false
}]